import { FC, PropsWithChildren } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const fontInter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

const RootLayout: FC<Readonly<PropsWithChildren>> = ({ children }): JSX.Element => {
   return (
      <html lang="en">
         <body className={fontInter.className}>{children}</body>
      </html>
   );
};

export default RootLayout;
